export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const AUTH_USER = 'AUTH_USER';
export const CLEAR_UPDATE_USER = 'CLEAR_UPDATE_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const GET_PRODUCTS_BY_ARRIVAL = 'GET_PRODUCTS_BY_ARRIVAL';
export const GET_PRODUCTS_BY_SELL = 'GET_PRODUCTS_BY_SELL';
export const GET_PRODUCTS_TO_SHOP = 'GET_PRODUCTS_TO_SHOP';

export const ADD_BRAND = 'ADD_BRAND';
export const GET_BRANDS = 'GET_BRANDS';
export const ADD_WOOD = 'ADD_WOOD';
export const GET_WOODS = 'GET_WOODS';

export const GET_SITE_DATA = 'GET_SITE_DATA';
export const UPDATE_SITE_DATA = 'UPDATE_SITE_DATA';
